### PR TITLE
Remove promote comments test (and variants)

### PR DESCRIPTION
**Pull request by nicl**
The corresponding code has already been removed from Frontend. See:

https://github.com/guardian/frontend/pull/14979
https://github.com/guardian/frontend/pull/14999

Notes on my first PR for discussion-frontend:

* the 1-css/JS file per component makes removing stuff very straightforward
* the code is very understandable, even for someone like me who isn't a client-side developer, although I did have to familiarise myself with some of the ECMA 2015 features (the spread operator and destructuring being the main two)
* testing this was very simple and much nicer than battling with Frontend - although it is still important to understand how changes relate to Frontend, so you can't escape it completely

cc @guardian/discussion @gtrufitt

### CODE REVIEW

**Comment by gtrufitt** [comment]
Do you need to release this as a version and update the CHANGELOG?

**Comment by piuccio** [comment]
😎  I only regret not adding unit tests

Out of curiosity, which variant won?

**Comment by nicl** [comment]
@gtrufitt yep, I still need to do that! Thanks.

**Comment by nicl** [comment]
@piuccio just asking Chris about the actual results (it's been off for a little while now).

Re: versioning, were you going for SemVer? Technically this is a backwards-incompatible change so I should bump the version to 2.0 if you were.

**Comment by crifmulholland** [comment]
@piuccio I'm not sure what we set up as the completion event, but between preact and react, it changed each day. Neither were significant 'winners' and the difference between was negligible.

**Comment by crifmulholland** [comment]
The bubble and top banner were the more successful at promoting comments. Neither had particularly significant changes in affecting frequency, but all saw a rise in frequency when present.

**Pull request merged**
