### PR TITLE
Check in built code

### PR DESCRIPTION
**Pull request by SiAdcock**
In the near future, we will be using Webpack to bundle our Frontend code, which means we will no longer have a global `require` that we can rely on to load external modules.

To help facilitate this, we have decided in that short term that it would be useful to install Discussion  Frontend into the Frontend as a module. Webpack can then bundle Discussion Frontend like any other published library.

The simplest way to achieve this is to bundle and commit built code into the Discussion Frontend repo, and have Frontend install it directly from GitHub.

@sndrs @nicl @gtrufitt

### CODE REVIEW

**Comment by nicl** [comment]
@SiAdcock let's chat about this in our meeting because I'm not sure I understand all the implications here!

**Comment by piuccio** [comment]
This goes against one of the main reason why discussion frontend is a separate repo.
The whole point was the ability to deploy discussion without having to deploy frontend, in other words discussion is not bundled together with frontend.

In the future you might not have a global `require` but you'll always have a way of loading external things, maybe `System.import()` or `import()` or whatever your bundler comes with. All you need to know is the path to the deployed file

**Comment by sndrs** [comment]
the plan is to install this (for now by `<git remote url>#<commit/tag>` but ideally by release number) into frontend's `package.json`, so we can load it from there however we need. we can revisit that later if work resumes on this, but currently this repo is unlikely to see any changes and depends on frontend providing an AMD loader...

to my mind, this reveals a particular problem with decoupling code in this way (load vs install) in that they _aren't_ entirely decoupled. how frontend bundles its js should be _it's_ concern, but as things stand, frontend depends (in part) on how _discussion_ bundles _its_ js. currently we need updated discussion libs  just so that we can change our module bundler... 🏃‍♀️  🏃

discussion frontend is decoupled from frontend but not vice versa 

to compound that, unless we bundle some kind of universal loader, the only way we can interact with anything we load remotely is on a global somewhere. 

the hope is that this should avoid all of that while leaving discussion to be developed/deployed independently of frontend...?

**Comment by piuccio** [comment]
Unfortunately things are never completely decoupled, imagine you're using disqus, here's how you set it up:

```html
<div id="disqus_thread"></div>

<script>
var disqus_config = function () {
   this.page.url = PAGE_URL;
   this.page.identifier = PAGE_IDENTIFIER;
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//theguardian-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
```

In other words you need a DOM placeholder, a way to load a script and a mechanism to pass configuration.
Discussion works in exactly the same way with the only difference being the script loaded via AMD.

If AMD is your problem, the solution is not to bundle the two together, but to change the format.

The [rollup configuration](https://github.com/guardian/discussion-frontend/blob/master/rollup.config.preact.amd.js#L5) exports `amd` for convenience, if webpack works better with UMD, just change that line to `umd` or add a new configuration file.

Have a look at `assets.json` it looks like this

```json
{
   "discussion-frontend.preact.amd":"discussion-frontend.preact.amd.e34499b4c4.js",
   "discussion-frontend.react.amd":"discussion-frontend.react.amd.cd24be9958.js",
   "riffraff.build.id":"dev"
}
```
it tells you all the formats it generates and the corresponding path, you can always add new one

```json
{
   "discussion-frontend.preact.amd":"discussion-frontend.preact.amd.e34499b4c4.js",
   "discussion-frontend.preact.umd":"discussion-frontend.preact.umd.35134211a.js",
   "discussion-frontend.preact.iife":"discussion-frontend.preact.iife.asd987349a.js",
}
```

and let your loader pick whatever it knows how to handle

**Comment by SiAdcock** [comment]
You make a good point @piuccio. Although we can't load external files using Webpack, we can load them using the `load-script` module in frontend. Then the problem becomes the fact that `discussion-frontend` is bundled using the AMD output format and hence assumes a global `define` exists.

There is a wider question around coupling, versioning and dependency management, but let's talk about that outside of this PR.

I'll raise an alternative PR that bundles `discussion-frontend` using the UMD output format and attaches the resulting exportable to the global object.

**Pull request closed without merging**
